# Generated by Django 4.0.5 on 2022-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studyplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('deadline', models.DateField()),
                ('cardsets_to_study', models.ManyToManyField(related_name='study_plans', to='flashcards.cardset')),
            ],
        ),
    ]
